name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - master

jobs:
  publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      shell: pwsh
      run: |
        # Create artifacts
        dir "src/**/*.csproj" -Recurse | %{ dotnet publish $PSItem.FullName -c Release -o publish/win-x64 -r win-x64 --no-self-contained }
        dir "src/**/*.csproj" -Recurse | %{ dotnet publish $PSItem.FullName -c Release -o publish/win-x86 -r win-x86 --no-self-contained }
        
        # Compress them into zip archives
        Compress-Archive -Path publish/win-x64/* -DestinationPath win-x64.zip
        Compress-Archive -Path publish/win-x86/* -DestinationPath win-x86.zip
    - uses: dev-drprasad/delete-tag-and-release@v1.0.1
      with:
        delete_release: true # default: false
        tag_name: nightly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag commit
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        
        git tag -a "nightly" -m "nightly release"
        git push --tags
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly
        name: "nightly"
        files: |
          win-x86.zip
          win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
